### ISSUE TITLE
Rng [Random] Command - If arguments are not numbers

### ISSUE THREAD

**Issue by Shwibi** [ToasterLLC/R2D2-bot-discord#1]
If arguments are not numbers in `rng` command, the bot may just send "undefined" back to the user, and you will get an error message in the console.

The bot will not tell the user what the issue was, in this file:
![image](https://user-images.githubusercontent.com/63779128/125650320-7f7ab427-3c6c-4f84-9e55-71af13ee3853.png)

At line 5, there should be a check for if both arguments are numbers using `isNaN()` function, or any other way.

Cheers!

**Comment by ToasterLLC** [comment]
Thanks for pointing it out :)
