### ISSUE TITLE
ERROR: Command handling will not work if commandName is invalid, and command doesn't exist

### ISSUE THREAD

**Issue by Shwibi** [ToasterLLC/R2D2-bot-discord#4]
In the file `R2D2-bot-discord/events/guild/message.js`, this is the snippet:
```js
//Original code as per 25/07/2021@2307 without modifications
const config = require ("../../config.json");

module.exports = (Discord, client, message) => {

    if (!message.content.startsWith(config.prefix) || message.author.bot) return;

    const args = message.content.slice(config.prefix.length).split(" ");
    const commandName = args.shift().toLowerCase();
    const command = client.commands.get(commandName);

    if (commandName) {
        command.execute(client, message, args, Discord);
    }
}
```

Here, you are checking for `commandName` and not `command`. If this is the case, everytime a user types in a wrong command, there will be an error in the console and the user will not be notified. You should check if the `command` exists and then carry out the command, instead of the `commandName`.

For example, if I type the command `rd!blah` it will not do anything in the chat, but there will be an error in the console. Because here the `commandName` variable is `blah` while the `command` variable is `undefined`.

This snippet might be better,

```js
//Modified snippet on 25/07/2021@2310
const config = require ("../../config.json");

module.exports = (Discord, client, message) => {

    if (!message.content.startsWith(config.prefix) || message.author.bot) return;

    const args = message.content.slice(config.prefix.length).split(" ");
    const commandName = args.shift().toLowerCase();
    const command = client.commands.get(commandName);

    if (command) {
        command.execute(client, message, args, Discord);
    }
}
```

Hope this helped, good luck!

**Comment by ToasterLLC** [comment]
Fixed in df65e9f
